### ISSUE TITLE
More than one instance on the same page?

### ISSUE THREAD

**Issue by framerate** [compedit/react-youtube#22]
When I use more than one on the same page, only the 2nd one works. 

Any ideas why?

**Comment by compedit** [comment]
Weird, it probably has something to do with the event handlers having to be globalized.

I'll take look and update you on anything I find

**Comment by framerate** [comment]
Also, if you read this @compedit have you gotten the full screen button to show up in an embed?

```
let opts = {
            width: 800,
            height: 459,
            playerVars: {
                autoplay: 1,
                fs: 1
            }
        };
```

seems to be as instructed but it doesn't show up.

**Comment by KeweiCodes** [comment]
I'm currently looking at this problem too. Would be nice to get it fixed soon. :/

**Comment by KeweiCodes** [comment]
From a bit more of my testing, I've found that it's always the last react-youtube component which is rendered. For some reason, calling:
**new window.YT.Player(props.id, params)**
doesn't actually *return* unless it's targeted at the last component...

**Comment by compedit** [comment]
I think I've got it,  rough version of it [here](https://github.com/compedit/react-youtube/blob/multiple-instances-fix/src/lib/createPlayer.js), with a demo on [jsbin](http://output.jsbin.com/dusotugito). Would you all mind making sure the demo works on your machines too? 

Turns out `window.onYouTubeIframeAPIReady` was being redefined with every single player creation, so when the API actually loaded only the last component/player was notified which is super not cool.

@framerate fs should be enabled by default, it's working [here](http://troybetz.com/react-youtube/). It might be getting cancelled out inside of `createPlayer`when set explicitly though, I'll check it out right now while cleaning up

@KeweiCodes I'll try to get a release out in the next day or so, just going to clean up the code a little bit and write some tests, should have a release out by tomorrow night latest. 

Update here when finished, thanks for the help so far!

**Comment by framerate** [comment]
@compedit Unfortunately I refactored my code so that it creates the instance on-demand to get past this bug. Once I finish this deadline though, I'm more than happy to try and help test it. I'll let you know, but update this thread if you do a release and I'll at least get it into my package.json to test backwards compat.

**Comment by compedit** [comment]
Everything should work perfectly now!
